export const states = [
  {title: 'Alabama', value: 'AL', id: 'AL', key: 'AL'},
  {title: 'Alaska', value: 'AK', id: 'AK', key: 'AK'},
  {title: 'Arizona', value: 'AZ', id: 'AZ', key: 'AZ'},
  {title: 'Arkansas', value: 'AR', id: 'AR', key: 'AR'},
  {title: 'California', value: 'CA', id: 'CA', key: 'CA'},
  {title: 'Colorado', value: 'CO', id: 'CO', key: 'CO'},
  {title: 'Connecticut', value: 'CT', id: 'CT', key: 'CT'},
  {title: 'Delaware', value: 'DE', id: 'DE', key: 'DE'},
  {title: 'Florida', value: 'FL', id: 'FL', key: 'FL'},
  {title: 'Georgia', value: 'GA', id: 'GA', key: 'GA'},
  {title: 'Hawaii', value: 'HI', id: 'HI', key: 'HI'},
  {title: 'Idaho', value: 'ID', id: 'ID', key: 'ID'},
  {title: 'Illinois', value: 'IL', id: 'IL', key: 'IL'},
  {title: 'Indiana', value: 'IN', id: 'IN', key: 'IN'},
  {title: 'Iowa', value: 'IA', id: 'IA', key: 'IA'},
  {title: 'Kansas', value: 'KS', id: 'KS', key: 'KS'},
  {title: 'Kentucky', value: 'KY', id: 'KY', key: 'KY'},
  {title: 'Louisiana', value: 'LA', id: 'LA', key: 'LA'},
  {title: 'Maine', value: 'ME', id: 'ME', key: 'ME'},
  {title: 'Maryland', value: 'MD', id: 'MD', key: 'MD'},
  {title: 'Massachusetts', value: 'MA', id: 'MA', key: 'MA'},
  {title: 'Michigan', value: 'MI', id: 'MI', key: 'MI'},
  {title: 'Minnesota', value: 'MN', id: 'MN', key: 'MN'},
  {title: 'Mississippi', value: 'MS', id: 'MS', key: 'MS'},
  {title: 'Missouri', value: 'MO', id: 'MO', key: 'MO'},
  {title: 'Montana', value: 'MT', id: 'MT', key: 'MT'},
  {title: 'Nebraska', value: 'NE', id: 'NE', key: 'NE'},
  {title: 'Nevada', value: 'NV', id: 'NV', key: 'NV'},
  {title: 'New Hampshire', value: 'NH', id: 'NH', key: 'NH'},
  {title: 'New Jersey', value: 'NJ', id: 'NJ', key: 'NJ'},
  {title: 'New Mexico', value: 'NM', id: 'NM', key: 'NM'},
  {title: 'New York', value: 'NY', id: 'NY', key: 'NY'},
  { title: 'North Carolina', value: 'NC', id: 'NC', key: 'NC' },
  {title: 'North Dakota', value: 'ND', id: 'ND', key: 'ND'},
{title: 'Ohio', value: 'OH', id: 'OH', key: 'OH'},
{title: 'Oklahoma', value: 'OK', id: 'OK', key: 'OK'},
{title: 'Oregon', value: 'OR', id: 'OR', key: 'OR'},
{title: 'Pennsylvania', value: 'PA', id: 'PA', key: 'PA'},
{title: 'Rhode Island', value: 'RI', id: 'RI', key: 'RI'},
{title: 'South Carolina', value: 'SC', id: 'SC', key: 'SC'},
{title: 'South Dakota', value: 'SD', id: 'SD', key: 'SD'},
{title: 'Tennessee', value: 'TN', id: 'TN', key: 'TN'},
{title: 'Texas', value: 'TX', id: 'TX', key: 'TX'},
{title: 'Utah', value: 'UT', id: 'UT', key: 'UT'},
{title: 'Vermont', value: 'VT', id: 'VT', key: 'VT'},
{title: 'Virginia', value: 'VA', id: 'VA', key: 'VA'},
{title: 'Washington', value: 'WA', id: 'WA', key: 'WA'},
{title: 'West Virginia', value: 'WV', id: 'WV', key: 'WV'},
{title: 'Wisconsin', value: 'WI', id: 'WI', key: 'WI'},
  { title: 'Wyoming', value: 'WY', id: 'WY', key: 'WY' }
  
];
